# Generated by Django 4.1.4 on 2022-12-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('edit_date', models.DateField(blank=True, verbose_name='date edited')),
                ('source_code_url', models.URLField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=100)),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
    ]
