# Generated by Django 4.1.4 on 2022-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.DateField(blank=True, null=True, verbose_name='date edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_code_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='website_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
