# Generated by Django 4.1.4 on 2022-12-15 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_post_edit_date_remove_post_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='languages',
            field=models.TextField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 20, 26, 323623, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
