# Generated by Django 4.1.4 on 2022-12-15 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_languages_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='program_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 31, 6, 533802, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 31, 6, 533802, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
