# Generated by Django 4.1.4 on 2022-12-16 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_post_program_date_alter_post_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='program_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 2, 29, 56, 275216, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 2, 29, 56, 275216, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
