# Generated by Django 4.1.4 on 2022-12-28 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_post_program_date_alter_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='languages',
            new_name='technologies_used',
        ),
        migrations.AlterField(
            model_name='post',
            name='program_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 7, 55, 46, 85466, tzinfo=datetime.timezone.utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 7, 55, 46, 85466, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
